config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users
  resources :sessions

  delete '/logout' => 'sessions#destroy', as: :logout

  namespace :admin do
    root 'sessions#new'
    resources :sessions
    resources :categories
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  before_create :set_default_attr

  private
  def set_default_attr
    self.uudi = RandomCode.generate_product_uuid
  end
end

app/models/user.rb
# coding: utf-8
class User < ApplicationRecord
  authenticates_with_sorcery!

  attr_accessor :password, :password_confirmaiton

  validates_presence_of :email, message: "邮箱不能为空"
  validates_format_of :email, message: "邮箱格式不合法", 
    with: /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/,
    if: proc { |user| !user.email.blank? }
 
  validates :email, uniqueness: true

  validates_presence_of :password, message: "密码不能为空",
                        if: :need_validate_password
  validates_presence_of :password_confirmation, message: "密码确认不能为空",
                        if: :need_validate_password
  validates_confirmation_of :password, message: "密码不一致",
                            if: :need_validate_password
  validates_length_of :password, message: "密码最短为6位", minimum: 6,
                      if: :need_validate_password


  def username
    self.email.split('@').first
  end
  private
  def need_validate_password
    self.new_record? ||
      (!self.password.nil? || !self.password_confirmation.nil?)
  end
  validates :email, uniqueness: true


end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base

  layout 'admin/layouts/admin'

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.roots.page(params[:page] || 1).per_page(params[:per_page] || 10).order(id: "desc")
  end

  def new
    @category = Category.new
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::BaseController 
  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
# -*- coding: utf-8 -*-
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = login(params[:email], params[:password])
      flash[:notice] = "登陆成功"
      redirect_to root_path
    else
      flash[:notice] = "邮箱或者密码不正确"
      redirect_to new_session_path
    end
  end

  def destroy
    logout
    flash[:notice] = "退出成功"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user)
      .permit(:email, :password, :password_confirmation))

    if @user.save
      flash[:notice] = "注册成功，请登录"
      redirect_to new_session_path
    else
      render action: :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/categories/index.html.erb
<div>
    <div class="pull-right">
        <%= link_to "新建分类", new_admin_category_path, class: "btn btn-primary" %>
    </div>

    <h1>
        <% if @category %>
            分类:<%= @category.title %>(<%= @categories.total_entries %>)
        <% else %>
            分类(<%= @categories.total_entries %>)
        <% end -%>
    </h1>
</div>

<div>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>名称</th>
            <th>Weight</th>
            <th></th>
        </tr>

        <% @categories.each do |category| %>
            <tr>
                <td><%= category.id %></td>
                <td><%= category.title %></td>
                <td><%= category.weight %></td>
                <td align="right">
                    <%= link_to "编辑", edit_admin_category_path(category) %> 
                    <%= link_to "删除", admin_category_path(category), method: :delete, 'data-confirm': "确认删除吗?" %>
                    <% if category.root? %>
                        <%= link_to "查看子分类", admin_categories_path(id: category) %>
                    <% end -%>
                </td>
            </tr>
        <% end -%>
    </table>

    <%= will_paginate @categories %>
</div>

app/views/admin/categories/new.html.erb
<div>
    <h1><%= @category.new_record? ? "新建分类" : "修改分类 ##{params[:id]}" %></h1>
</div>

<div class="form-body">
    <%= form_for @category, 
        url: (@category.new_record? ? admin_categories_path : admin_category_path(@category)), 
        method: (@category.new_record? ? 'post' : 'put'), 
        html: { class: 'form-horizontal' } do |f| %>

        <% unless @category.errors.blank? %>
            <div class="alert alert-danger">
                <ul class="list-unstyled">
                    <% @category.errors.messages.values.flatten.each do |error| %>
                        <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
                    <% end -%>
                </ul>
            </div>
        <% end -%>

        <div class="form-group">
            <label for="ancestry" class="col-sm-2 control-label">所属分类:</label>
            <div class="col-sm-5">
                <select name="category[ancestry]">
                    <option></option>
                    <% @root_categories.each do |category| %>
                        <% next if category == @category %>
                        <option value="<%= category.id %>" <%= @category.ancestry == category.id.to_s ? 'selected' : '' %>><%= category.title %></option>
                    <% end -%>
                </select>
                为空为一级分类
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">名称:*</label>
            <div class="col-sm-5">
                <%= f.text_field :title, class: "form-control" %>
            </div>
        </div>
        <div class="form-group">
            <label for="weight" class="col-sm-2 control-label">权重:</label>
            <div class="col-sm-5">
                <%= f.text_field :weight, class: "form-control" %> 数值越大越靠前
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <%= f.submit (@category.new_record? ? "新建分类" : "编辑分类"), class: "btn btn-default" %>
            </div>
        </div>
    <% end -%>
</div>

app/views/admin/layouts/_menu.html.erb
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= admin_root_path %>">管理平台</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<%= admin_root_path %>">Home <span class="sr-only">(current)</span></a></li>
                <li><a href="<%= admin_categories_path %>">分类</a></li>
            </ul>
        </div>
    </div>
</nav>

app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>管理平台 - 蛋人商城</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag 'admin', media: 'all' %>
        <%= yield :stylesheets %>
    </head>

    <body>
        <%= render 'admin/layouts/menu' %>
        <div class="container">
            <% unless flash[:notice].blank? %>
                <div class="alert alert-info"><%= flash[:notice] %></div>
            <% end -%>
            
            <%= yield %>
        </div>

        <%= javascript_include_tag 'admin' %>
        <%= yield :javascripts %>
    </body>
</html>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">蛋人商城</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_path %>">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">分类</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="商品名称..">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">购物车</a></li>
        <% unless logged_in? %>
            <li><a href= "<%= new_user_path %>">注册</a></li>
            <li><a href= "<%= new_session_path %>">登录</a></li>
        <% else %>
            <li>
                <a href="#">欢迎你, <%= current_user.username %></a>
            </li>
            <li><%= link_to "退出", logout_path, method: :delete %></li>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">个人中心 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">我的订单</a></li>
            <li><a href="#">我的收获地址</a></li>
            <li><a href="#">我的收藏</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">个人信息</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>B2C 商城</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= yield :stylesheets %>
  </head>

  <body>
    <%= render 'layouts/menu' %>
      <div class="container">
          <% unless flash[:notice].blank? %>
            <div class="alert alert-info"><%= flash[:notice] %></div>
          <% end -%>

      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= yield :javascript %>
  </body>
</html>

app/views/users/new.html.erb
<h1>注册</h1>
<% unless @user.errors.empty? %>
    <div class="alert alert-danger">
        <ul>
            <% @user.errors.messages.values.flatten.each do |error| %>
                <li><%= error %></li>
            <% end -%>
        </ul>
    </div>
<% end -%>

<%= form_for :user, url: users_path, method: :post, html: { class: 'form-horizontal', id: "user_form"} do |f| %>
    <div class="form-group">
        <div class="col-lg-12">邮箱 *</div>
        <div class="col-lg-12">
            <%= f.text_field :email, class: "form-control" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-12">密码 *</div>
        <div class="col-lg-12">
            <%= f.password_field :password, class: "form-control" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-12">密码确认 *</div>  
        <div class="col-lg-12">
            <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-12">
            <input type="submit" name="create_user_submit" value="创建账户" class="col-xs-12 btn btn-primary"> 
        </div>
    </div>
<% end -%>

app/views/welcome/index.html.erb
<h1>首页</h1>